# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: smmf name

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

 

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: build project
      run: npm run build --if-present
    - name: Test it
      run: npm test

  johnbeynon:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
              api-key: ${{ secrets.MY_RENDER_API_KEY }}
            